# Form implementation generated from reading ui file 'd:\GYANTS\G\github\sd2-stocksradar\assets\gui\newsitem.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 186)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.container = QtWidgets.QWidget(parent=Form)
        self.container.setObjectName("container")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.container)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cont_layout = QtWidgets.QGridLayout()
        self.cont_layout.setHorizontalSpacing(10)
        self.cont_layout.setVerticalSpacing(5)
        self.cont_layout.setObjectName("cont_layout")
        self.Time = QtWidgets.QLabel(parent=self.container)
        self.Time.setObjectName("Time")
        self.cont_layout.addWidget(self.Time, 1, 1, 1, 1)
        self.Headline = QtWidgets.QLabel(parent=self.container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Headline.setFont(font)
        self.Headline.setText("")
        self.Headline.setObjectName("Headline")
        self.cont_layout.addWidget(self.Headline, 0, 0, 1, 3)
        self.Source = QtWidgets.QLabel(parent=self.container)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Source.setFont(font)
        self.Source.setObjectName("Source")
        self.cont_layout.addWidget(self.Source, 1, 0, 1, 1)
        self.SentimentLabel = QtWidgets.QLabel(parent=self.container)
        self.SentimentLabel.setObjectName("SentimentLabel")
        self.cont_layout.addWidget(self.SentimentLabel, 1, 2, 1, 1)
        self.Summary = QtWidgets.QLabel(parent=self.container)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Summary.setFont(font)
        self.Summary.setText("")
        self.Summary.setWordWrap(True)
        self.Summary.setObjectName("Summary")
        self.cont_layout.addWidget(self.Summary, 2, 0, 1, 3)
        self.cont_layout.setColumnStretch(0, 1)
        self.cont_layout.setColumnStretch(1, 1)
        self.cont_layout.setColumnStretch(2, 2)
        self.cont_layout.setRowStretch(0, 3)
        self.cont_layout.setRowStretch(1, 2)
        self.cont_layout.setRowStretch(2, 6)
        self.gridLayout_2.addLayout(self.cont_layout, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.container, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Time.setText(_translate("Form", "asdasda"))
        self.Source.setText(_translate("Form", "sddadasda"))
        self.SentimentLabel.setText(_translate("Form", "asdas"))
